### PR TITLE
fix(nvim): using wrong colorscheme

### PR DESCRIPTION
**Pull request by Woife5**
Hey! I noticed an issue in your dotfiles and wanted to help you out. Hope this helps!

### CODE REVIEW

**Comment by ahetzm** [comment]
LGTM

**Comment by dasbaumwolltier** [comment]
LGTM 👍

**Comment by DaDaniB** [comment]
LGTM 👍

**Comment by Stoiko96** [comment]
LGTM 👍

**Comment by Stoiko96** [comment]
Looks good to me :)

**Comment by manujell73** [comment]
LGTM ✨

**Pull request closed without merging**
